name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * 1' # Weekly on Monday at 2 AM

jobs:
  dependency-scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run npm audit (production dependencies)
      run: npm audit --omit=dev --audit-level=moderate
      
    - name: Run npm audit (all dependencies)
      run: npm audit --audit-level=high
      continue-on-error: true
      
    - name: Check for outdated packages
      run: npm outdated || true
